cache:
  directories:
    - $HOME/.m2

language: java

jdk:
  - openjdk17

branches:
  only:
    - main

services:
  - docker

stages:
  - test
  - deploy

install: skip

jobs:
  include:
    - stage: test
      name: "Testing Application"
      services: postgresql
      before_script:
        - psql -c 'CREATE DATABASE productcatalog;' -U postgres
      script:
        - make test

    - stage: deploy
      name: "Deploy Application to Production"
      script:
        - make deploy

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL